/**
 * Heartbeat Decision Loop
 *
 * Main entry point for the heartbeat runtime. Accepts a HeartbeatSignal,
 * builds runtime snapshot, plans candidate intents, evaluates hard guards,
 * and returns a HeartbeatCycleResult.
 *
 * Per design doc §4.3: heartbeat round follows the sequence:
 * signal → snapshot → plan → guard → result (HEARTBEAT_OK or intent_selected)
 *
 * Per ADR-005: heartbeat is the free-rhythm main entry; this loop
 * implements the default conservative path where HEARTBEAT_OK is
 * the first-class result when no action is warranted.
 */
import type {
  HeartbeatSignal,
  HeartbeatCycleResult,
  HeartbeatCycleStatus,
  RuntimeScope,
  RuntimeTrigger,
} from "./signal.js";
import type {
  CandidateIntent,
  ContinuitySnapshot,
  IntentKind,
} from "../types.js";
import {
  buildContinuitySnapshot,
  type SnapshotInputs,
} from "./snapshot-builder.js";
import {
  buildHeartbeatRuntimeSnapshot,
  type HeartbeatRuntimeSnapshot,
} from "./runtime-snapshot.js";
import { planCandidateIntents } from "../orchestrator/intent-planner.js";
import { applyGoalPriority } from "../orchestrator/goal-priority.js";
import { evaluateHardGuards } from "../orchestrator/guard-layer.js";
import type { GuidanceDraftPort } from "../../../guidance/outreach-draft-schema.js";
import type { StateDatabase } from "../../../storage/db/index.js";
import {
  dispatchUserOutreachIntent,
  type OpenClawDeliveryPort,
} from "../outreach/dispatch-user-outreach.js";
import { buildJudgeOutreachInputFromSnapshot } from "../outreach/judge-input-from-snapshot.js";
import { runSourceBackedQuiet } from "../quiet/run-source-backed-quiet.js";
import type { ConnectorExecutor } from "../../../connectors/base/contract.js";
import { toCapabilityIntent } from "../orchestrator/effect-dispatcher.js";
import type { NarrativeStateStore } from "../../../storage/narrative/narrative-state-store.js";
import { updateNarrativeAfterEffect } from "../orchestrator/narrative-update.js";

export interface HeartbeatDecisionTracePayload {
  scope: RuntimeScope;
  status: HeartbeatCycleStatus;
  reasons: string[];
  selectedIntentId?: string;
  rhythmWindowId: string;
  allowedIntentKinds: IntentKind[];
  candidateCount: number;
  lifeEvidenceEmpty: boolean;
  trigger: RuntimeTrigger;
}

/** Optional outreach delivery chain: when set, first allowed `user_outreach` runs dispatch (CR-M1). */
export interface HeartbeatOutreachDispatchDeps {
  state: StateDatabase;
  guidance: GuidanceDraftPort;
  delivery: OpenClawDeliveryPort;
}

/** Optional Quiet orchestration: when set, quiet/reflection allows run source-backed Quiet writer (T2.3.3). */
export interface HeartbeatQuietWorkflowDeps {
  workspaceRoot: string;
}

/**
 * Resolves the heartbeat outcome for a guard-allowed intent (outreach dispatch, quiet orchestration, or default).
 * Exported for unit tests (CR-M1 wiring).
 */
export async function resolveAllowedIntentResult(
  intent: CandidateIntent,
  runtime: HeartbeatRuntimeSnapshot,
  inputs: SnapshotInputs,
  signal: HeartbeatSignal,
  deps: Pick<
    HeartbeatDeps,
    "outreachDispatch" | "quietWorkflow" | "connectorExecutor"
  >,
): Promise<HeartbeatCycleResult> {
  const day =
    typeof signal.payload.timestamp === "string"
      ? signal.payload.timestamp.slice(0, 10)
      : "1970-01-01";
  if (intent.effectClass === "user_outreach" && deps.outreachDispatch) {
    return dispatchUserOutreachIntent({
      candidate: intent,
      snapshot: runtime,
      judgeInput: buildJudgeOutreachInputFromSnapshot(intent, runtime, inputs),
      guidance: deps.outreachDispatch.guidance,
      delivery: deps.outreachDispatch.delivery,
      state: deps.outreachDispatch.state,
    });
  }
  if (
    deps.quietWorkflow &&
    (intent.kind === "quiet" ||
      (intent.kind === "reflection" &&
        intent.effectClass === "narrative_reflection"))
  ) {
    const quietRun = await runSourceBackedQuiet({
      candidate: intent,
      runtime,
      day,
      userInterestSnapshot: inputs.userInterestSnapshot,
      workspaceRoot: deps.quietWorkflow.workspaceRoot,
    });
    return quietRun.result;
  }
  // T2.2.3 (CH-14-02/03 / CH-15-01): all intent_selected results must carry at least one
  // machine-readable reason so operators can distinguish between effect classes:
  //   - maintenance / no_effect → "internal_tick" (no external side-effects)
  //   - connector_action without dispatch wired → "connector_dispatch_unwired"
  //   - external_platform_action / memory_curation → not generated by intent-planner today;
  //     if a future path produces them, they will reach the fallback [] branch below and
  //     should have dedicated reason codes added (e.g. "external_platform_action_unwired").
  //   - other (outreach / quiet) → caught by the early-return branches above
  const noExternalEffect =
    intent.effectClass === "maintenance" ||
    intent.effectClass === "no_effect" ||
    intent.kind === "maintenance";
  const connectorUnwired = intent.effectClass === "connector_action";

  if (connectorUnwired && deps.connectorExecutor) {
    const result = await deps.connectorExecutor.executeEffect({
      platformId: intent.platformId ?? "unknown",
      intent: toCapabilityIntent(intent),
      payload: {},
      decisionId: `decision:${intent.id}:${Date.now()}`,
      intentId: intent.id,
      idempotencyKey: `idem:${intent.id}:${Date.now()}`,
    });
    const base: HeartbeatCycleResult = {
      scope: "rhythm",
      status: "intent_selected",
      selectedIntentId: intent.id,
      decisionId: `decision:${intent.id}:${Date.now()}`,
      reasons:
        result.status === "success"
          ? ["connector_effect_executed"]
          : result.status === "retryable_failure"
            ? ["connector_retryable_failure", result.failureClass ?? "unknown"]
            : ["connector_terminal_failure", result.failureClass ?? "unknown"],
    };
    return base;
  }

  const reasons: string[] = noExternalEffect
    ? ["internal_tick"]
    : connectorUnwired
      ? ["connector_dispatch_unwired"]
      : [];
  return {
    scope: "rhythm",
    status: "intent_selected",
    selectedIntentId: intent.id,
    reasons,
  };
}

export interface HeartbeatDeps {
  /** Load snapshot inputs from state-system */
  loadSnapshotInputs: () => Promise<SnapshotInputs>;
  /** Optional observability hook (T2.2.1): one record per completed cycle. */
  recordDecisionTrace?: (
    payload: HeartbeatDecisionTracePayload,
  ) => Promise<void>;
  outreachDispatch?: HeartbeatOutreachDispatchDeps;
  quietWorkflow?: HeartbeatQuietWorkflowDeps;
  /**
   * When present, guard-allowed connector_action intents are dispatched
   * through the connector-system instead of returning connector_dispatch_unwired.
   */
  connectorExecutor?: ConnectorExecutor;
  /** T2.1.5: when present, heartbeat writes a source-backed NarrativeState revision after each cycle. */
  narrativeStateStore?: NarrativeStateStore;
}

/**
 * T2.1.5: after the cycle result is known, write a narrative revision when
 * a NarrativeStateStore is wired. Errors are swallowed so the cycle result
 * is never blocked by a store failure.
 */
async function maybeUpdateNarrativeState(
  result: HeartbeatCycleResult,
  selectedIntent: CandidateIntent | undefined,
  runtime: HeartbeatRuntimeSnapshot,
  store: NarrativeStateStore | undefined,
): Promise<void> {
  if (!store) return;
  try {
    const prior = await store.loadNarrativeState();
    const update = updateNarrativeAfterEffect({
      result,
      selectedIntent,
      lifeEvidence: runtime.lifeEvidence,
      priorNarrative: prior,
    });
    await store.updateNarrativeState(update);
  } catch {
    // degrade silently; narrative update is best-effort
  }
}

/**
 * Ingest a heartbeat rhythm signal and drive one full decision round.
 */
export async function ingestRhythmSignal(
  signal: HeartbeatSignal,
  deps: HeartbeatDeps,
): Promise<HeartbeatCycleResult> {
  const inputs = await deps.loadSnapshotInputs();
  const snapshot = buildContinuitySnapshot(inputs);
  const timestamp = signal.payload.timestamp;
  const runtime = buildHeartbeatRuntimeSnapshot(timestamp, inputs, snapshot);
  const rawCandidates = planCandidateIntents(runtime);
  const { candidates } = applyGoalPriority(rawCandidates, inputs.acceptedGoals);

  const emitTrace = async (result: HeartbeatCycleResult): Promise<void> => {
    if (!deps.recordDecisionTrace) return;
    await deps.recordDecisionTrace({
      scope: result.scope,
      status: result.status,
      reasons: result.reasons,
      selectedIntentId: result.selectedIntentId,
      rhythmWindowId: runtime.rhythmWindow.windowId,
      allowedIntentKinds: [...runtime.rhythmWindow.allowedIntentKinds],
      candidateCount: candidates.length,
      lifeEvidenceEmpty:
        runtime.lifeEvidence.evidenceRefs.length === 0 &&
        runtime.lifeEvidence.platformEventCount === 0 &&
        runtime.lifeEvidence.workEventCount === 0,
      trigger: signal.trigger,
    });
  };

  let hasCandidates = false;
  let anyAllow = false;
  let anyDefer = false;
  let anyDeny = false;
  const denyReasons: string[] = [];

  for (const intent of candidates) {
    hasCandidates = true;
    const evaluation = evaluateHardGuards(intent, runtime);
    if (evaluation.verdict === "allow") {
      anyAllow = true;
      const base: HeartbeatCycleResult = {
        scope: "rhythm",
        status: "intent_selected",
        selectedIntentId: intent.id,
        reasons: evaluation.reasons,
      };
      const resolved = await resolveAllowedIntentResult(
        intent,
        runtime,
        inputs,
        signal,
        deps,
      );
      const result: HeartbeatCycleResult =
        resolved.status === "intent_selected" &&
        resolved.reasons.length === 0 &&
        evaluation.reasons.length > 0
          ? { ...resolved, reasons: evaluation.reasons }
          : resolved;

      await emitTrace(result);
      await maybeUpdateNarrativeState(
        result,
        intent,
        runtime,
        deps.narrativeStateStore,
      );
      return result;
    }
    if (evaluation.verdict === "defer") {
      anyDefer = true;
      denyReasons.push(
        `${intent.id}:${evaluation.verdict}(${evaluation.reasons.join(",")})`,
      );
      continue;
    }
    anyDeny = true;
    denyReasons.push(
      `${intent.id}:${evaluation.verdict}(${evaluation.reasons.join(",")})`,
    );
  }

  if (!hasCandidates) {
    const result: HeartbeatCycleResult = {
      scope: "rhythm",
      status: "heartbeat_ok",
      reasons: ["silent_no_candidates"],
    };
    await emitTrace(result);
    await maybeUpdateNarrativeState(
      result,
      undefined,
      runtime,
      deps.narrativeStateStore,
    );
    return result;
  }

  if (!anyAllow && anyDefer && !anyDeny) {
    const result: HeartbeatCycleResult = {
      scope: "rhythm",
      status: "deferred",
      reasons:
        denyReasons.length > 0 ? denyReasons : ["all_candidates_deferred"],
    };
    await emitTrace(result);
    await maybeUpdateNarrativeState(
      result,
      undefined,
      runtime,
      deps.narrativeStateStore,
    );
    return result;
  }

  if (!anyAllow && denyReasons.length > 0) {
    const result: HeartbeatCycleResult = {
      scope: "rhythm",
      status: "denied",
      reasons: denyReasons,
    };
    await emitTrace(result);
    await maybeUpdateNarrativeState(
      result,
      undefined,
      runtime,
      deps.narrativeStateStore,
    );
    return result;
  }

  const result: HeartbeatCycleResult = {
    scope: "rhythm",
    status: "heartbeat_ok",
    reasons: ["no_allow_verdict"],
  };
  await emitTrace(result);
  await maybeUpdateNarrativeState(
    result,
    undefined,
    runtime,
    deps.narrativeStateStore,
  );
  return result;
}

/**
 * Build a snapshot directly from inputs (for testing or when state-system is unavailable).
 */
export function buildSnapshotFromInputs(
  inputs: SnapshotInputs,
): ContinuitySnapshot {
  return buildContinuitySnapshot(inputs);
}
