import fs from "node:fs";
import path from "node:path";
function resolveConnectorsDir(workspaceRoot) {
    if (workspaceRoot) {
        return path.resolve(workspaceRoot, ".second-nature", "connectors");
    }
    return path.resolve(process.cwd(), ".second-nature", "connectors");
}
function generateManifestYaml(input) {
    const platformId = input.platformId;
    const displayName = input.displayName ?? platformId;
    const family = input.family ?? "custom";
    const runnerKind = input.runnerKind ?? "declarative_http";
    const baseUrlLine = input.baseUrl ? `\nbaseUrl: ${input.baseUrl}` : "";
    return `schemaVersion: sn.connector.v1
platformId: ${platformId}
displayName: ${displayName}
family: ${family}${baseUrlLine}
capabilities:
  - id: ${platformId}.placeholder
    description: Placeholder capability — replace with real capability declarations
runner:
  kind: ${runnerKind}
  entrypoint: ""
credentials: []
sourceRefPolicy:
  minSourceRefs: 1
  rejectInlineSensitivePayload: true
trust:
  status: custom_adapter_pending_trust
  reason: generated_by_connector_init
`;
}
function generateAdapterStub(platformId) {
    const pascalId = platformId
        .split(/[-_]/)
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
        .join("");
    return `/**
 * ${pascalId} Connector Adapter Stub
 *
 * Generated by \`second-nature connector init\`.
 * Replace this stub with real platform-specific execution logic.
 *
 * Runner kind: custom_adapter (pending trust until owner allowlists).
 */

import type { ConnectorResult } from "@second-nature/connector-sdk";

export interface ${pascalId}AdapterConfig {
  baseUrl: string;
  apiKey?: string;
}

export async function execute${pascalId}Action(
  config: ${pascalId}AdapterConfig,
  action: string,
  payload: unknown,
): Promise<ConnectorResult> {
  // TODO: implement real platform call
  return {
    ok: false,
    error: {
      code: "NOT_IMPLEMENTED",
      message: \`${pascalId} adapter action '\${action}' is not yet implemented\`,
    },
  };
}
`;
}
function generateTypesStub(platformId) {
    const pascalId = platformId
        .split(/[-_]/)
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
        .join("");
    return `/**
 * ${pascalId} Connector Type Stubs
 *
 * Generated by \`second-nature connector init\`.
 * Expand these types as you add real capabilities.
 */

export interface ${pascalId}Capability {
  id: string;
  description?: string;
}

export interface ${pascalId}Credential {
  type: "api_key" | "oauth" | "session";
  required: boolean;
}

export interface ${pascalId}PlatformPayload {
  // TODO: define real platform-specific payload shapes
  [key: string]: unknown;
}
`;
}
export async function connectorInit(input) {
    const { platformId, force = false } = input;
    if (!platformId || typeof platformId !== "string" || platformId.trim().length === 0) {
        return {
            ok: false,
            platformId: "",
            manifestPath: "",
            adapterPath: "",
            typesPath: "",
            created: false,
            reason: "platformId is required and must be a non-empty string",
        };
    }
    const trimmed = platformId.trim();
    if (trimmed === "." || trimmed === "..") {
        return {
            ok: false,
            platformId: trimmed,
            manifestPath: "",
            adapterPath: "",
            typesPath: "",
            created: false,
            reason: "platformId cannot be '.' or '..'",
        };
    }
    const sanitized = trimmed.replace(/[^a-zA-Z0-9_-]/g, "_");
    if (sanitized !== trimmed) {
        return {
            ok: false,
            platformId,
            manifestPath: "",
            adapterPath: "",
            typesPath: "",
            created: false,
            reason: `platformId contains invalid characters. Suggested: ${sanitized}`,
        };
    }
    const connectorsDir = resolveConnectorsDir(input.workspaceRoot);
    const platformDir = path.join(connectorsDir, sanitized);
    const manifestPath = path.join(platformDir, "manifest.yaml");
    const adapterPath = path.join(platformDir, "adapter.ts");
    const typesPath = path.join(platformDir, "types.ts");
    // CR7-01: fail-closed when target already exists (no silent skip)
    if (fs.existsSync(manifestPath) && !force) {
        return {
            ok: false,
            platformId: sanitized,
            manifestPath,
            adapterPath,
            typesPath,
            created: false,
            reason: "manifest already exists; use force:true to overwrite",
        };
    }
    fs.mkdirSync(platformDir, { recursive: true });
    const manifestContent = generateManifestYaml({ ...input, platformId: sanitized });
    fs.writeFileSync(manifestPath, manifestContent, "utf-8");
    const adapterContent = generateAdapterStub(sanitized);
    fs.writeFileSync(adapterPath, adapterContent, "utf-8");
    const typesContent = generateTypesStub(sanitized);
    fs.writeFileSync(typesPath, typesContent, "utf-8");
    return {
        ok: true,
        platformId: sanitized,
        manifestPath,
        adapterPath,
        typesPath,
        created: true,
    };
}
